### ISSUE TITLE
Not showing loading icon in Meteor + Vue 3 App

### ISSUE THREAD

**Issue by jmrunge** [HELMAB/vue-loading#28]
Hi! Im trying to use your component in my Meteor+Vue app. I installed the component with 
`meteor npm i --save vue3-loading-screen`

Then, I added it to my `main.js`

> import { Meteor } from "meteor/meteor";
import { createApp } from "vue";
import { VueMeteor } from "vue-meteor-tracker";
import Loading from "vue3-loading-screen";

> import App from "./App.vue";
import { router } from "./router";

> Meteor.startup(() => {
  const app = createApp(App);
  app.use(router);
  app.use(VueMeteor);
  app.use(Loading, /*{...}*/);
  app.mount("#app");
});

In my `App.vue` file, I am importing Fontawesome this way:
> import '@fortawesome/fontawesome-free';
import '@fortawesome/fontawesome-free/css/all.css';
import '@fortawesome/fontawesome-free/js/all.js';

And then, I have a component which is referenced this way:
`<template>
... 
  <ConfigForm :config="config" />
...
</template>`

Inside this component is where I want to set Loading to true or false. 
In `script setup` I have this code:
> import { Meteor } from 'meteor/meteor';
import { ref, inject } from 'vue';
import '@fortawesome/fontawesome-free/css/all.css';

>const isLoading = inject('changeStatus');
...
const save = () => {
  isLoading(true);
  Meteor.call(
    ...
    isLoading(false);
  );
};

When I call `isLoading(true);` screen gets blocked, until I call `isLoading(false);`, but not Loading Icon is shown. 
I already checked the issue where someone asked a similiar question, but I think I have correct fontawesome installed and referenced. Also, his question I think was for vue 2.

Could you help me please to find what is wrong? I already checked for error messages in chrome console and didnt found any.

Thanks in advance!

**Comment by HELMAB** [comment]
Sorry @jmrunge for the late reply. I think maybe you have a conflict font awesome version or maybe you can try to inspect loading icon is correct or not. For more detail, you can visit this link: https://www.npmjs.com/package/vue3-loading-screen

**Comment by jmrunge** [comment]
Hi @HELMAB ! Thanks for the response... The "tailwind example" in the NPMJS page hitted the problem. It seems Tailwind/VUE/Meteor (dont know which one really) transforms the \<i> into \<svg> internally, so using the "slot" option was the trick.

If it is not much asking, can I ask you to point me in how to change the text dinamically? I woule like to use your component globaly, but would be nice to show some text according the operation... lets say, if the "long" operation is uploading a file, have it to say "Uploading"... If it is saving a record to DB, "Saving"... I think something with the "changeIsLoadingOptions", but am no really sure how to do it. 

Kind Regards and thanks again for the support!

**Comment by HELMAB** [comment]
Yes, @jmrunge I think you can use `changeIsLoadingOptions` function to change the txt dynamically. 

Suppose you've configured the loading option to like this

```js
import { createApp } from 'vue'
import App from './App.vue'
import loading from 'vue3-loading-screen'

const app = create(App)
    .use(loading, {
        slot: "<div>Loading</div>"
    })
    .mount('#app')
```

So you can change your text from "Loading" to "Uploading" with the example below

```js
<template>
  <h1>Your UI</h1>
</template>

<script setup>
import {inject} from "vue"

const changeStatus = inject('changeStatus')
const changeIsLoadingOptions = inject('changeIsLoadingOptions')

const sendHttpRequest = () => {
    changeIsLoadingOptions({ slot: "<div>Uploading</div>" })
    changeStatus(true)
}
</script>
```

**Comment by jmrunge** [comment]
> Yes, @jmrunge I think you can use `changeIsLoadingOptions` function to change the txt dynamically.
> 
> Suppose you've configured the loading option to like this
> 
> ```js
> import { createApp } from 'vue'
> import App from './App.vue'
> import loading from 'vue3-loading-screen'
> 
> const app = create(App)
>     .use(loading, {
>         slot: "<div>Loading</div>"
>     })
>     .mount('#app')
> ```
> 
> So you can change your text from "Loading" to "Uploading" with the example below
> 
> ```js
> <template>
>   <h1>Your UI</h1>
> </template>
> 
> <script setup>
> import {inject} from "vue"
> 
> const changeStatus = inject('changeStatus')
> const changeIsLoadingOptions = inject('changeIsLoadingOptions')
> 
> const sendHttpRequest = () => {
>     changeIsLoadingOptions({ slot: "<div>Uploading</div>" })
>     changeStatus(true)
> }
> </script>
> ```

Hi! Thanks for your support and sorry for late response.... Was quite bussy in other projects. I finally managed to do it based on your idea and its working like expected! 

Thank you very much!
