### ISSUE TITLE
TypeError in mounted hook

### ISSUE THREAD

**Issue by rimakan** [HELMAB/vue-loading#4]
Hi! I'm new in Vue JS and I've got a question. I am using Ruby on Rails plus VueJS 2

I'm facing the error "this.$isLoading is not a function. (In 'this.$isLoading(true)', 'this.$isLoading' is undefined)". I did everything according to readme provided. What do I need to do to get rid of this error?

The code: https://gyazo.com/3b48327ef9c1c8370e2bbc248e5e06f6
The error in browser: https://gyazo.com/5d8489592ae77749c51b963eb1471294

**Comment by HELMAB** [comment]
Hi @rimakan 

Could I see your installation code?

**Comment by rimakan** [comment]
Sure thing, here you go: https://gyazo.com/2800730657d50f3161b3b6c7ff772cc2

Do I need to have axios installed? I saw you using it in the read me code example (...$axios)

**Comment by HELMAB** [comment]
Could you try to move the plugin before the initial Vue instance?

**Comment by rimakan** [comment]
I moved the plugin (Vue.use(loading), I guess) and I see this loading screen. I have a new type error now: https://gyazo.com/eebb49dd58639e9db0582d3bf22a04b6

How can I deal with this error? Do I need to install axios?

**Comment by HELMAB** [comment]
Yes, you can use any HTTP Client Library, but in the example I used Axios.

**Comment by rimakan** [comment]
Thank you. So, how can I cope with this error?

**Comment by HELMAB** [comment]
@rimakan Can you try to move your `Vue.prototype.$http = axios` to the top before the initial Vue instance? and you can call replace  `this.$axios` with  `this.$http`
```vue
<script>
export default {
  methods: {
    your_method_name () {
        this.$isLoading(true)
        this.$http.post(url, params)
          .then(() => { 
             // do something
          })
          .catch((err) => console.log(err))
          .finally(() => this.$isLoading(false))
      }
  }
}
</script>
```

**Comment by rimakan** [comment]
I did it and it works fine, thank you for helping me and having developed this great library :)
